branches:
  only:
  - master

language: python
python:
#  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  # PyPy versions
  - "pypy3.7"
# command to install dependencies
install:
  - pip install -r pywisp/requirements.txt
  - pip install .
# command to run tests
script: pytest
